CREATE TABLE [dbo].[Player]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
	[LeagueTeam] UNIQUEIDENTIFIER NOT NULL,
    [Name] NVARCHAR(50) NOT NULL, 
	[Status] NVARCHAR(50) NULL, 
	[Team] UNIQUEIDENTIFIER NULL, 
    [Position] INT NOT NULL, 
	[Bye] INT NULL, 
    [Fan Pts] FLOAT NULL, 
    [PassingYards] INT NULL, 
	[PassingTouchdowns] Int NULL,
	[PassingInterceptions] Int NULL,
	[RushingAttempts] Int NULL,
	[RushingYards] INT NULL, 
	[RushingTouchdowns] Int NULL,
	[Targets] Int NULL,
	[Receptions] Int NULL,
    [ReceivingYards] INT NULL, 
	[ReceivingTouchdowns] INT NULL, 
	[ReturnTouchdowns] INT NULL, 
	[TwoPointConversions] INT NULL, 
    [Fumbles] INT NULL, 
	[FieldGoals0-19] INT Null,
	[FieldGoals20-29] INT Null,
	[FieldGoals30-39] INT Null,
	[FieldGoals40-49] INT Null,
	[FieldGoals50] INT Null,
	[Made] INT Null,
	[PointsAllowed] INT Null,
	[Sack] INT Null,
	[Safety] INT Null,
	[Interceptions] INT Null,
	[FumbleRecovery] INT Null,
	[Touchdowns] INT Null,
	[BlockKick] INT Null,
	[KickoffAndPuntReturnTouchdown] INT Null,
	CONSTRAINT [FK_Player_ToLeagueTeam] FOREIGN KEY (LeagueTeam) REFERENCES [LeagueTeam]([Id]),
    CONSTRAINT [FK_Player_ToPSportsTeam] FOREIGN KEY (Team) REFERENCES [SportsTeam]([Id]),
	CONSTRAINT [FK_Player_ToBasePlayer] FOREIGN KEY (Id) REFERENCES [BasePlayer]([Id])
)
